export const categories = [
  "Technology",
  "Business",
  "Science",
  "Health",
  "Politics",
  "Entertainment",
  "Sports",
  "Environment",
  "Education",
  "World"
];

export const newsItems = [
  {
    id: 1,
    title: "SpaceX Successfully Launches New Satellite Constellation",
    category: "Technology",
    source: "Space News",
    timeAgo: "2 hours ago",
    comments: 128,
    shares: 456,
    className: "md:col-span-2 md:row-span-2",
  },
  {
    id: 2,
    title: "Global Markets React to Economic Policy Changes",
    category: "Business",
    source: "Financial Times",
    timeAgo: "1 hour ago",
    comments: 89,
    shares: 234,
    className: "md:col-span-1 md:row-span-1",
  },
  {
    id: 3,
    title: "Breakthrough in Renewable Energy Storage",
    category: "Science",
    source: "Science Daily",
    timeAgo: "3 hours ago",
    comments: 156,
    shares: 789,
    className: "md:col-span-1 md:row-span-1",
  },
  {
    id: 4,
    title: "New AI Model Achieves Human-Level Performance",
    category: "Technology",
    source: "Tech Review",
    timeAgo: "4 hours ago",
    comments: 234,
    shares: 567,
    className: "md:col-span-2 md:row-span-1",
  },
  {
    id: 5,
    title: "Climate Summit Reaches Historic Agreement",
    category: "Environment",
    source: "Global News",
    timeAgo: "5 hours ago",
    comments: 445,
    shares: 1023,
    className: "md:col-span-1 md:row-span-2",
  },
];